name: Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          cache: true

      - name: Setup Android SDK
        run: |
          echo "y" | sdkmanager --install "platforms;android-34" "build-tools;34.0.0" || true
          echo "y" | sdkmanager --licenses || true

      - name: Clean Flutter cache
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Fix flutter_blue_plus_android plugin
        shell: bash
        run: |
          set -e
          # Find flutter_blue_plus_android plugin
          PLUG_DIR=$(find "$HOME/.pub-cache/hosted" -type d -path "*flutter_blue_plus_android*" | head -n 1 || true)
          echo "Plugin dir: $PLUG_DIR"
          if [ -n "$PLUG_DIR" ] && [ -f "$PLUG_DIR/android/build.gradle" ]; then
            echo "Fixing flutter_blue_plus_android build.gradle..."
            GRADLE_FILE="$PLUG_DIR/android/build.gradle"
            # Ensure compileSdkVersion is set
            if ! grep -q "compileSdkVersion" "$GRADLE_FILE"; then
              sed -i '/android {/a \\    compileSdkVersion 34' "$GRADLE_FILE"
            else
              sed -i -E 's/compileSdkVersion[[:space:]]+[0-9]+/compileSdkVersion 34/' "$GRADLE_FILE" || true
            fi
            # Fix flutter extension references that may be null
            sed -i 's/flutter\.compileSdkVersion/34/g' "$GRADLE_FILE" || true
            sed -i 's/flutter\.targetSdkVersion/34/g' "$GRADLE_FILE" || true
            sed -i 's/flutter\.minSdkVersion/21/g' "$GRADLE_FILE" || true
            echo "Fixed flutter_blue_plus_android plugin"
          fi

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: smart-insole-app
          path: build/app/outputs/flutter-apk/app-release.apk
