name: Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          cache: true

      - name: Clean Flutter cache
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Force compileSdk/targetSdk 34 in plugin and app
        run: |
          set -e
          # Patch app build.gradle to ensure SDK 34
          sed -i 's/compileSdkVersion .*/compileSdkVersion 34/' android/app/build.gradle || true
          sed -i 's/targetSdkVersion .*/targetSdkVersion 34/' android/app/build.gradle || true
          # Patch flutter_bluetooth_serial plugin if present
          PLUG_DIR=$(find "$HOME/.pub-cache/hosted" -type d -path "*flutter_bluetooth_serial*" | head -n 1 || true)
          if [ -n "$PLUG_DIR" ]; then
            GRADLE_FILE="$PLUG_DIR/android/build.gradle"
            if [ -f "$GRADLE_FILE" ]; then
              sed -i 's/compileSdkVersion .*/compileSdkVersion 34/' "$GRADLE_FILE" || true
              sed -i 's/targetSdkVersion .*/targetSdkVersion 34/' "$GRADLE_FILE" || true
            fi
          fi

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: smart-insole-app
          path: build/app/outputs/flutter-apk/app-release.apk
