name: Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          cache: true

      - name: Clean Flutter cache
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Patch flutter_bluetooth_serial to use SDK 34
        shell: bash
        run: |
          set -e
          PLUG_DIR=$(find "$HOME/.pub-cache/hosted" -type d -path "*flutter_bluetooth_serial-*/android" | head -n 1 || true)
          echo "Plugin android dir: $PLUG_DIR"
          if [ -n "$PLUG_DIR" ] && [ -f "$PLUG_DIR/build.gradle" ]; then
            sed -i -E 's/compileSdkVersion[[:space:]]+[0-9]+/compileSdkVersion 34/' "$PLUG_DIR/build.gradle" || true
            sed -i -E 's/targetSdkVersion[[:space:]]+[0-9]+/targetSdkVersion 34/' "$PLUG_DIR/build.gradle" || true
            # If minSdkVersion missing or too low, ensure at least 21
            grep -q "minSdkVersion" "$PLUG_DIR/build.gradle" || sed -i '/defaultConfig[[:space:]]*{/a \\        minSdkVersion 21' "$PLUG_DIR/build.gradle"
          fi

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: smart-insole-app
          path: build/app/outputs/flutter-apk/app-release.apk
